//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.24 at 09:46:24 AM CET 
//


package nl.naturalis.lims2.oaipmh.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.naturalis.lims2.oaipmh.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.naturalis.lims2.oaipmh.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Geneious }
     * 
     */
    public Geneious createGeneious() {
        return new Geneious();
    }

    /**
     * Create an instance of {@link Specimen }
     * 
     */
    public Specimen createSpecimen() {
        return new Specimen();
    }

    /**
     * Create an instance of {@link DNASlide }
     * 
     */
    public DNASlide createDNASlide() {
        return new DNASlide();
    }

    /**
     * Create an instance of {@link DNAExtract }
     * 
     */
    public DNAExtract createDNAExtract() {
        return new DNAExtract();
    }

    /**
     * Create an instance of {@link Amplification }
     * 
     */
    public Amplification createAmplification() {
        return new Amplification();
    }

    /**
     * Create an instance of {@link DNALabProject }
     * 
     */
    public DNALabProject createDNALabProject() {
        return new DNALabProject();
    }

    /**
     * Create an instance of {@link SpecimenUnit }
     * 
     */
    public SpecimenUnit createSpecimenUnit() {
        return new SpecimenUnit();
    }

    /**
     * Create an instance of {@link ExtractUnit }
     * 
     */
    public ExtractUnit createExtractUnit() {
        return new ExtractUnit();
    }

    /**
     * Create an instance of {@link SlideUnit }
     * 
     */
    public SlideUnit createSlideUnit() {
        return new SlideUnit();
    }

    /**
     * Create an instance of {@link GeneticAccession }
     * 
     */
    public GeneticAccession createGeneticAccession() {
        return new GeneticAccession();
    }

    /**
     * Create an instance of {@link Sequencing }
     * 
     */
    public Sequencing createSequencing() {
        return new Sequencing();
    }

}
