//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.24 at 09:46:24 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://data.naturalis.nl/lims2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.naturalis.lims2.oaipmh.jaxb;
