//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.21 at 11:29:42 AM CET 
//


package nl.naturalis.lims2.oaipmh.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sequencing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sequencing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cloningStaff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consensusSequenceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="consensusSequenceLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="consensusSequenceQuality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amplificationStaff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="geneticAccession" type="{http://data.naturalis.nl/lims2}GeneticAccession"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sequencing", propOrder = {
    "cloningStaff",
    "consensusSequenceID",
    "consensusSequenceLength",
    "consensusSequenceQuality",
    "amplificationStaff",
    "geneticAccession"
})
public class Sequencing {

    @XmlElement(required = true)
    protected String cloningStaff;
    @XmlElement(required = true)
    protected String consensusSequenceID;
    protected int consensusSequenceLength;
    @XmlElement(required = true)
    protected String consensusSequenceQuality;
    @XmlElement(required = true)
    protected String amplificationStaff;
    @XmlElement(required = true)
    protected GeneticAccession geneticAccession;

    /**
     * Gets the value of the cloningStaff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloningStaff() {
        return cloningStaff;
    }

    /**
     * Sets the value of the cloningStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloningStaff(String value) {
        this.cloningStaff = value;
    }

    /**
     * Gets the value of the consensusSequenceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsensusSequenceID() {
        return consensusSequenceID;
    }

    /**
     * Sets the value of the consensusSequenceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsensusSequenceID(String value) {
        this.consensusSequenceID = value;
    }

    /**
     * Gets the value of the consensusSequenceLength property.
     * 
     */
    public int getConsensusSequenceLength() {
        return consensusSequenceLength;
    }

    /**
     * Sets the value of the consensusSequenceLength property.
     * 
     */
    public void setConsensusSequenceLength(int value) {
        this.consensusSequenceLength = value;
    }

    /**
     * Gets the value of the consensusSequenceQuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsensusSequenceQuality() {
        return consensusSequenceQuality;
    }

    /**
     * Sets the value of the consensusSequenceQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsensusSequenceQuality(String value) {
        this.consensusSequenceQuality = value;
    }

    /**
     * Gets the value of the amplificationStaff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmplificationStaff() {
        return amplificationStaff;
    }

    /**
     * Sets the value of the amplificationStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmplificationStaff(String value) {
        this.amplificationStaff = value;
    }

    /**
     * Gets the value of the geneticAccession property.
     * 
     * @return
     *     possible object is
     *     {@link GeneticAccession }
     *     
     */
    public GeneticAccession getGeneticAccession() {
        return geneticAccession;
    }

    /**
     * Sets the value of the geneticAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneticAccession }
     *     
     */
    public void setGeneticAccession(GeneticAccession value) {
        this.geneticAccession = value;
    }

}
